/* eslint-disable no-empty */
// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
const Services = {}; loadServices();
const chrome = require('chromedriver');

//  _   _  _         _      _                     _          _
// | \ | |(_)       | |    | |                   | |        | |
// |  \| | _   __ _ | |__  | |_ __      __  __ _ | |_   ___ | |__
// | . ` || | / _` || '_ \ | __|\ \ /\ / / / _` || __| / __|| '_ \
// | |\  || || (_| || | | || |_  \ V  V / | (_| || |_ | (__ | | | |
// \_| \_/|_| \__, ||_| |_| \__|  \_/\_/   \__,_| \__| \___||_| |_|
//             __/ |
//            |___/

module.exports = {
  // An array of folders (excluding subfolders) where your tests are located;
  // if this is not specified, the test source must be passed as
  // the second argument to the test runner.
  src_folders: ['tests'],
  output_folder: 'tests_output',
  skip_testcases_on_fail: false,
  // Parallel running stuff:
  detailed_output: true,
  live_output: true,
  test_workers: {
    'enabled': false,
    'workers': 5
  },


  // See https://nightwatchjs.org/guide/working-with-page-objects/
  page_objects_path: ['./pages'],

  // See https://nightwatchjs.org/guide/extending-nightwatch/#writing-custom-commands
  custom_commands_path: ['./commands'],

  // See https://nightwatchjs.org/guide/extending-nightwatch/#writing-custom-assertions
  custom_assertions_path: ['./assertions'],

  // See https://nightwatchjs.org/guide/#external-globals
  globals_path: '',

  webdriver: {},

  test_settings: {
    default: {
      launch_url: '',
      globals: {
        waitForConditionTimeout: 30000,
      },

      screenshots: {
        enabled: true,
        path: 'tests_output/screens',
        on_failure: true
      },

      desiredCapabilities: {
        browserName: 'chrome'
      },

      webdriver: {
        start_process: true,
        server_path: ''
      }
    },

    'chrome': {
      desiredCapabilities: {
        browserName: 'chrome',
        'goog:chromeOptions': {
          // More info on Chromedriver: https://sites.google.com/a/chromium.org/chromedriver/
          //
          // w3c:false tells Chromedriver to run using the legacy
          // JSONWire protocol (not required in Chrome 78)
          w3c: true,
          args: [
            '--profile-directory=Default',
            '--ignore-certificate-errors',
            '--allow-insecure-localhost',
            'window-size=1920,1080',
            // '--headless',
            '--no-sandbox',
            '--disable-dev-shm-usage',
            '--disable-default-apps'
          ]
        }
      },

      webdriver: {
        start_process: true,
        port: 9515,
        server_path: (Services.chromedriver ? Services.chromedriver.path : chrome.path),
        log_path: 'tests_output/logs',
        cli_args: [
          // --verbose
        ]
      }
    }
  }
};

/**
 * loadService function
 */
function loadServices() {
  try {
    Services.seleniumServer = require('selenium-server');
  } catch (err) { }

  try {
    Services.chromedriver = require('chromedriver');
  } catch (err) { }

  try {
    Services.geckodriver = require('geckodriver');
  } catch (err) { }
}
